name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Create environment files
        run: |
          cp ./src/environments/environment.template.ts ./src/environments/environment.ts
          cp ./src/environments/environment.prod.template.ts ./src/environments/environment.prod.ts
          sed -i 's/TMDB_TOKEN_PLACEHOLDER/${{ secrets.TMDB_TOKEN }}/g' ./src/environments/environment.ts
          sed -i 's/TMDB_TOKEN_PLACEHOLDER/${{ secrets.TMDB_TOKEN }}/g' ./src/environments/environment.prod.ts

      - name: Build
        run: ng build --configuration production --base-href "https://roxana-hgh.github.io/Moodflix/"

      - name: Deploy
        run: npx angular-cli-ghpages --dir=dist/moodflix/browser --no-silent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}